name: Deploy production
on:
  schedule:
    - cron: "20 18 * * *"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the Netlify build hook
      env:
        DEPLOY_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        DEPLOY_TRIGGER: ${{ github.event_name }}
      run: |
        chmod +x ./bin/deploy
        ./bin/deploy production
